# Generated by Django 6.0 on 2026-01-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('short_term', 'Last 4 weeks'), ('medium_term', 'Last 6 months'), ('long_term', 'All time')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_tracks', to='analytics.listeningsnapshot')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_snapshots', to='analytics.track')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('snapshot', 'position')},
            },
        ),
    ]
